#Conexión con MySQL
spring.application.name=empresa
spring.datasource.url=jdbc:mysql://localhost:3306/new_schema
spring.datasource.username=root
spring.datasource.password=

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Thymeleaf (Sin caché en desarrollo)
spring.thymeleaf.cache=false

#Aplicación de consola
spring.main.web-application-type=servlet
